language: node_js
node_js:
  - 16

git:
  depth: 1

# Install Dependencies
install:
  - npm i -g yarn
  - yarn install --frozen-lockfile

# Mount required file and Run Test and coverage
script:
  - echo $FAKE_BACKEND_CONFIG > src/GarnBarnApiConfig.json
  - yarn test:unit
  - yarn test:coverage

# Submit Coverage result
after_script:
  - codecov
