name: Vue Test
# Run test on every Push or Pull Request
on: [push, pull_request]

jobs:
  Test-Coverage:
    name: "Test & Coverage"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set up Cypress dependency
        run: |
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install Dependency
        run: yarn install --frozen-lockfile
      - name: "Mount Firebase Config File"
        run: |
          echo "$FIREBASE_SERVICE_CONFIG" > src/firebaseConfig.json
        shell: bash
        env:
          FIREBASE_SERVICE_CONFIG: ${{secrets.FIREBASE_SERVICE_CONFIG}}
      - name: "Mount GarnBarn Backend Config File"
        run: |
          echo "$GARNBARN_BACKEND_CONFIG" > src/GarnBarnApiConfig.json
        shell: bash
        env:
          GARNBARN_BACKEND_CONFIG: ${{secrets.GARNBARN_BACKEND_CONFIG}}
      - name: "Mount Firebase Service Account for Cypress Test"
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccount.json
        shell: bash
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{secrets.FIREBASE_SERVICE_ACCOUNT}}
      - name: Run Unit Test
        run: yarn test:unit
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge coverage data
        run: yarn merge-coverage
      - name: Submit coverage data to Codecov
        run: bash <(curl -s https://codecov.io/bash)
