name: Vue Test
# Run test on every Push or Pull Request
on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set up Cypress dependency
        run: |
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install Dependency
        run: yarn install --frozen-lockfile
      - name: "Mount Firebase Config File"
        run: |
          echo "$FIREBASE_SERVICE_CONFIG" > src/firebaseConfig.json
        shell: bash
        env:
          FIREBASE_SERVICE_CONFIG: ${{secrets.FIREBASE_SERVICE_CONFIG}}
      - name: "Mount GarnBarn Backend Config File"
        run: |
          echo "$GARNBARN_BACKEND_CONFIG" > src/GarnBarnApiConfig.json
        shell: bash
        env:
          GARNBARN_BACKEND_CONFIG: ${{secrets.GARNBARN_BACKEND_CONFIG}}
      - name: Run Unit Test
        run: yarn test:unit
      - name: Run Component Test
        run: yarn run cypress run-ct --record --key $CYPRESS_RECOARD_KEY
        env:
          CYPRESS_RECOARD_KEY: ${{secrets.CYPRESS_RECOARD_KEY}}

  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install Dependency
        run: yarn install --frozen-lockfile
      - name: "Mount Firebase Config File"
        run: |
          echo "$FIREBASE_SERVICE_CONFIG" > src/firebaseConfig.json
        shell: bash
        env:
          FIREBASE_SERVICE_CONFIG: ${{secrets.FIREBASE_SERVICE_CONFIG}}
      - name: "Mount GarnBarn Backend Config File"
        run: |
          echo "$GARNBARN_BACKEND_CONFIG" > src/GarnBarnApiConfig.json
        shell: bash
        env:
          GARNBARN_BACKEND_CONFIG: ${{secrets.GARNBARN_BACKEND_CONFIG}}
      - name: Run Coverage
        run: yarn test:coverage
      - name: Submit coverage data to Codecov
        run: bash <(curl -s https://codecov.io/bash)
